<?php
define('SKEBUILDER_START_TIME', array_sum(explode(' ', microtime())));


define('SKEBUILDER_FILES_DIR', SKEBUILDER_BASE . 'files' . SKEBUILDER_DS);

define('SKEBUILDER_CACHE_DIR', SKEBUILDER_FILES_DIR . 'cache' .  SKEBUILDER_DS);


define('SKEBUILDER_LIB_TEMPLATE', SKEBUILDER_BASE . 'lib' . DIRECTORY_SEPARATOR . 'template' . DIRECTORY_SEPARATOR);

define('SKEBUILDER_REPLACEMENT_MAPPING_FILE', SKEBUILDER_LIB_TEMPLATE . 'template_replacement_mapping.xml' );

define('SKEBUILDER_SRC_DIR', SKEBUILDER_BASE . 'src' . DIRECTORY_SEPARATOR);

define('SKEBUILDER_SKELETON_DIR', SKEBUILDER_BASE . 'lib' . DIRECTORY_SEPARATOR . 'skeleton' . DIRECTORY_SEPARATOR);

define('SKEBUILDER_RESOURCE_DIR', SKEBUILDER_BASE . 'tests' . DIRECTORY_SEPARATOR . 'resource' . DIRECTORY_SEPARATOR);

define('SKEBUILDER_STATIC_DIR', SKEBUILDER_BASE . 'static' . DIRECTORY_SEPARATOR );

define('SKEBUILDER_PHPFOX_SKELETON_LIB', SKEBUILDER_SKELETON_DIR . 'phpfox' . DIRECTORY_SEPARATOR );