<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-05 at 10:09:54.
 */
class contextTest extends PHPUnit_Framework_TestCase
{
    public function testGetListOfDirectoriesFromDirectory(){
         $context = new Context(SKEBUILDER_UNITTEST_EXPERIMENT_DIR);
         $mm_node = new FolderNode('mm');
         $context->push($mm_node);

         $test1_node = new FileNode('test1.txt');
         $context->push($test1_node);

         $actual = $context->getListOfDirectoriesFromDirectory('tests' . DIRECTORY_SEPARATOR . 'experiment');
         $expect = array('mm');
         $this->assertEquals($expect, $actual);
    }


    public function testGetListOfDirectoriesFromDirectory2(){
         $context = new Context(SKEBUILDER_UNITTEST_EXPERIMENT_DIR);
         $mm_node = new FolderNode('mm');
         $context->push($mm_node);

         $test1_node = new FileNode('test1.txt');
         $context->push($test1_node);

         $actual = $context->getListOfDirectoriesFromDirectory('tests');
         $expect = array('experiment', 'mm');
         $this->assertEquals($expect, $actual);
    }

}
