<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-05 at 11:23:30.
 */
class helpersTest extends PHPUnit_Framework_TestCase
{
	public function testGetFileList()
	{
		$helpers = new Helpers;
		$list = $helpers->getFileList(SKEBUILDER_UNITTEST_RESOURCE_DIR);
		$this->assertContains('test1.txt', $list[0]);
		$this->assertContains('test2.txt', $list[1]);
	}

	public function testStripFileExtension()
	{
		$helpers = new Helpers;
		$actual = $helpers->stripFileExtension('phpfox.php');
		$expected = 'phpfox';
		$this->assertEquals($actual, $expected);
	}
}
	