<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-05 at 11:23:30.
 */
class helpersTest extends PHPUnit_Framework_TestCase
{
	public function testGetFileList()
	{
		$helpers = new Helpers;
		$list = $helpers->getFileList(SKEBUILDER_UNITTEST_RESOURCE_DIR);
		$this->assertContains('mmtest1.txt', $list[0]);
		$this->assertContains('mmtest2.txt', $list[1]);
	}
}
	