<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-05 at 11:23:30.
 */
class parserTest extends PHPUnit_Framework_TestCase
{
	protected function tearDown()
    {
        Skebuilder::delete_directory(SKEBUILDER_UNITTEST_EXPERIMENT_DIR . 'upload');
    }

	/**
	 * @covers XMLparser->parse
	 */
	public function testParseAFile()
	{
		$xml_parser = new parser();
		$data = $xml_parser->parseSkeleton(SKEBUILDER_UNITTEST_SKELETON_DIR . 'unittest_default.xml');
		$data->create(SKEBUILDER_UNITTEST_EXPERIMENT_DIR);

		$print_visitor = new printVisitor;
		$data->accept($print_visitor);
		$this->assertTrue(count($data) > 0);
	}

		
}
