<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-05 at 11:23:30.
 */
class parserTest extends PHPUnit_Framework_TestCase
{
	protected function tearDown()
    {
        // Skebuilder::delete_directory(SKEBUILDER_UNITTEST_EXPERIMENT_DIR . 'upload');
    }

	// /**
	//  * @covers XMLparser->parse
	//  */
	// public function testParseAFile()
	// {
	// 	$xml_parser = new parser();
	// 	$data = $xml_parser->parseSkeleton(SKEBUILDER_UNITTEST_SKELETON_DIR . 'unittest_default.xml');
	// 	$data->create(SKEBUILDER_UNITTEST_EXPERIMENT_DIR);

	// 	$print_visitor = new printVisitor;
	// 	$data->accept($print_visitor);
	// 	$this->assertTrue(count($data) > 0);
	// }


	/**
	 * @covers XMLparser->parse
	 */
	// public function testParseWithVisitorPattern()
	// {
	// 	Skebuilder::setModuleName('jobposting');
	// 	$xml_parser = new parser();

	// 	$data = $xml_parser->parseSkeleton(SKEBUILDER_UNITTEST_SKELETON_DIR . 'unittest_default.xml');
	// 	$build_visitor = new buildVisitor(SKEBUILDER_UNITTEST_EXPERIMENT_DIR);
	// 	$data->accept($build_visitor);
	// 	// var_dump(Skebuilder::getErrorMessages());
	// }


	// public function testParseWithVisitorPattern2()
	// {
	// 	Skebuilder::setModuleName('jobposting');
	// 	Skebuilder::setPackageId('younet_jobposting');
	// 	$xml_parser = new parser();

	// 	// $data = $xml_parser->parseSkeleton(SKEBUILDER_UNITTEST_SKELETON_DIR . 'phpfox_default.xml');
	// 	$data = $xml_parser->parseSkeleton(SKEBUILDER_UNITTEST_SKELETON_DIR . 'phpfox_with_category.xml');
	// 	$build_visitor = new buildVisitor(SKEBUILDER_UNITTEST_EXPERIMENT_DIR);
	// 	$data->accept($build_visitor);
	// 	// var_dump(Skebuilder::getErrorMessages());
	// }
	// 
	// 
	// public function testParseAFile()
	// {
	// 	$context = new Context(SKEBUILDER_UNITTEST_EXPERIMENT_DIR);
	// 	$xml_parser = new parser();
	// 	$data = $xml_parser->parseSkeleton(SKEBUILDER_UNITTEST_SKELETON_DIR . 'unittest_default.xml');
		
	// 	$print_visitor = new printVisitor($context);
	// 	$data->accept($print_visitor);
	// 	// var_dump($data);
	// }

	public function testParseWithVisitorPattern1()
	{
		$context = new Context(SKEBUILDER_UNITTEST_EXPERIMENT_DIR);
		 $context->setModuleName('ynnews');
		 $context->setAuthorName('MinhTA');
		$xml_parser = new parser();

		$data = $xml_parser->parseSkeleton(SKEBUILDER_UNITTEST_SKELETON_DIR . 'oxwall/oxwall_ynnews.xml');
		$build_visitor = new buildVisitor($context);
		$data->accept($build_visitor);
		// 		$print_visitor = new printVisitor($context);
		// $data->accept($print_visitor);

		// var_dump(Skebuilder::getErrorMessages());
	}

		
}
