<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-05 at 11:23:30.
 */

define('SKEBUILDER_UNITTEST_PHPFOX_REPLACEMENT', SKEBUILDER_BASE_TEST . 'src' . DIRECTORY_SEPARATOR . 'replacement' . DIRECTORY_SEPARATOR);

require(SKEBUILDER_UNITTEST_PHPFOX_REPLACEMENT . 'ReplacementPhpfox.php');

class ReplacementPhpfoxTest extends PHPUnit_Framework_TestCase
{
    protected function tearDown()
    {
        // Skebuilder::delete_directory(SKEBUILDER_UNITTEST_EXPERIMENT_DIR . 'upload');
    }

    // /**
    //  * @covers XMLparser->parse
    //  */
    // public function testParseAFile()
    // {
    //  $xml_parser = new parser();
    //  $data = $xml_parser->parseSkeleton(SKEBUILDER_UNITTEST_SKELETON_DIR . 'unittest_default.xml');
    //  $data->create(SKEBUILDER_UNITTEST_EXPERIMENT_DIR);

    //  $print_visitor = new printVisitor;
    //  $data->accept($print_visitor);
    //  $this->assertTrue(count($data) > 0);
    // }


    /**
     * @covers XMLparser->parse
     */
    public function testReplacementPhpfoxModuleName()
    {
        Skebuilder::setModuleName('jobposting');
        $content = '';
        $replacement = new ReplacementPhpfox();
        $context = new Context(SKEBUILDER_UNITTEST_EXPERIMENT_DIR);
        $replacement->replace($content, $context);

        $replacement_list = $replacement->getReplacementList();
        $this->assertEquals('jobposting', $replacement_list['[skebuilder:module_name]']);
        // var_dump(Skebuilder::getErrorMessages());
    }


    public function testReplacementPhpfoxPackageId()
    {
        Skebuilder::setPackageId('younet_jobposting');
        $content = '';
        $replacement = new ReplacementPhpfox();
        $context = new Context(SKEBUILDER_UNITTEST_EXPERIMENT_DIR);
        $replacement->replace($content, $context);

        $replacement_list = $replacement->getReplacementList();
        $this->assertEquals('younet_jobposting', $replacement_list['[skebuilder:package_id]']);
        // var_dump(Skebuilder::getErrorMessages());
    }

        
}
