<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-05 at 11:23:30.
 */
class skeletonCollectionTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @covers skeletob::getSkeletonList
	 */
	public function testGetListOfSkeletons()
	{
		$skeletons = new SkeletonCollection(SKEBUILDER_UNITTEST_SKELETON_DIR);
		$skeleton_list = $skeletons->getSkeletonList();

		$this->assertTrue(in_array('phpfox_default', $skeleton_list));
		$this->assertTrue(in_array('se_default', $skeleton_list));
	}


	/**
	 * @covers skeleton::getSkeleton
	 */
	public function testGetSkeleton()
	{
		$skeletons = new SkeletonCollection(SKEBUILDER_UNITTEST_SKELETON_DIR);
		$phpfox_default_skeleton = $skeletons->getSkeleton('phpfox_default');
		$this->assertNotNull($phpfox_default_skeleton);
	}
	
	
}
