<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-05 at 11:23:30.
 */
class XMLparserTest extends PHPUnit_Framework_TestCase
{
	protected function tearDown()
    {
        Skebuilder::delete_directory(SKEBUILDER_UNITTEST_EXPERIMENT_DIR . 'upload');
    }

	/**
	 * @covers XMLparser->parse
	 */
	public function testParseAFile()
	{
		$xml_parser = new XMLparser();
		$data = $xml_parser->parse(SKEBUILDER_UNITTEST_SKELETON_DIR . 'unittest_default.xml');
		var_dump($data);
		var_dump(Skebuilder::getErrorMessages());
		$this->assertTrue(count($data) > 0);
	}

	
}
